export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const GET_API_DATA_START = 'GET_API_DATA_START';
export const GET_API_DATA_READY = 'GET_API_DATA_READY';
export const GET_API_DATA_ERROR = 'GET_API_DATA_ERROR';
export const SEARCH_QUERY_SUBMIT = 'SEARCH_QUERY_SUBMIT';